version: "3.0"
services: 
    master: 
        build: .
        volumes: 
            - ./conf/jupyter_notebook_config.py:/home/afoone/.jupyter/jupyter_notebook_config.py
            - ../docs:/home/afoone/
        ports: 
            - 8099:8080
        environment:
            - "VIRTUAL_HOST=master.once.mainserver.iprocuratio.com"
            - "VIRTUAL_PORT=8080"
        networks:
            - frontnet
    one: 
        build: .
        volumes: 
            - ./conf/jupyter_notebook_config.py:/home/afoone/.jupyter/jupyter_notebook_config.py
            - ../docs/one:/home/afoone/
        environment:
            - "VIRTUAL_HOST=one.once.mainserver.iprocuratio.com"
            - "VIRTUAL_PORT=8080"
        networks:
            - frontnet

networks: 
    frontnet:
        external:
            name: frontnet
        