version: "3.0"
services: 
    jupyter: 
        build: .
        volumes: 
            - ./conf/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
        ports: 
            - 8080:8080